sudo: required
services:
  - docker

before_install:
  - docker build -t ajdeleon/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ajdeleon/react-test npm test -- --coverage

after_success:
  - docker build -t ajdeleon/multi-client ./client
  - docker build -t ajdeleon/multi-nginx ./nginx
  - docker build -t ajdeleon/multi-server ./server
  - docker build -t ajdeleon/multi-worker ./worker

    # log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # push to docker hub
  - docker push ajdeleon/multi-client
  - docker push ajdeleon/multi-nginx
  - docker push ajdeleon/multi-server
  - docker push ajdeleon/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-741562941528
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
